"""Swarmbook additive modules."""

from .comparison import DraftComparator, DraftComparisonExport, render_comparison_markdown
from .config_loader import BookSimRoutingConfig
from .evidence_pack_builder import EvidencePackBuilder
from .graph_persistence import BookGraphPersistence, PersistenceResult
from .interrogation import PersonaInterrogationResult, PersonaInterrogator
from .local_cache import LocalArtifactCache
from .manuscript_chunker import ManuscriptChunker
from .platform_adapters import PLATFORM_ADAPTERS
from .report_builder import build_prediction_report
from .reader_archetype_loader import ReaderArchetypeCatalog, ReaderArchetypeLoader
from .reader_persona_generator import PersonaGenerationOverrides, ReaderPersonaGenerator
from .runtime_store import BookSimRuntimeStore, ProjectArtifactState
from .simulation import CrossReactionPass, PlatformReactionPass, PrivateReadingPass, SimulationOrchestrator
from .scoring import (
    ControversyScoreResult,
    ConfidenceBand,
    DNFScoreResult,
    PolarizationScoreResult,
    QuoteabilityScoreResult,
    RatingDistributionResult,
    RevisionPriorityItem,
    RevisionPriorityResult,
    ScoringContext,
    ViralScoreResult,
    score_controversy,
    score_dnf,
    score_polarization,
    score_quoteability,
    score_rating_distribution,
    score_revision_priority,
    score_viral_potential,
)
from .models import (
    BookDNA,
    BookPredictionReport,
    BookProject,
    ChapterMap,
    ChapterSummary,
    CharacterMap,
    CharacterProfile,
    ClaimMap,
    ClaimProfile,
    CrossReaction,
    DraftComparisonReport,
    EvidencePack,
    ManuscriptInput,
    MarketSurface,
    PlatformPost,
    PrivateReaderReaction,
    ReaderArchetype,
    ReaderPersona,
    RiskMap,
    RiskProfile,
    SimulationRun,
    StyleMap,
)
from .provider_router import BookSimProviderRouter, RouteSelection

__all__ = [
    "BookSimRoutingConfig",
    "DraftComparator",
    "DraftComparisonExport",
    "render_comparison_markdown",
    "LocalArtifactCache",
    "BookSimRuntimeStore",
    "ProjectArtifactState",
    "ManuscriptChunker",
    "EvidencePackBuilder",
    "BookGraphPersistence",
    "PersistenceResult",
    "build_prediction_report",
    "PersonaInterrogator",
    "PersonaInterrogationResult",
    "PLATFORM_ADAPTERS",
    "ReaderArchetypeCatalog",
    "ReaderArchetypeLoader",
    "ReaderPersonaGenerator",
    "PersonaGenerationOverrides",
    "PrivateReadingPass",
    "PlatformReactionPass",
    "CrossReactionPass",
    "SimulationOrchestrator",
    "ConfidenceBand",
    "ScoringContext",
    "RatingDistributionResult",
    "DNFScoreResult",
    "ViralScoreResult",
    "ControversyScoreResult",
    "QuoteabilityScoreResult",
    "PolarizationScoreResult",
    "RevisionPriorityItem",
    "RevisionPriorityResult",
    "score_rating_distribution",
    "score_dnf",
    "score_viral_potential",
    "score_controversy",
    "score_quoteability",
    "score_polarization",
    "score_revision_priority",
    "BookProject",
    "ManuscriptInput",
    "BookDNA",
    "ChapterMap",
    "ChapterSummary",
    "CharacterMap",
    "CharacterProfile",
    "ClaimMap",
    "ClaimProfile",
    "RiskMap",
    "RiskProfile",
    "StyleMap",
    "MarketSurface",
    "EvidencePack",
    "ReaderArchetype",
    "ReaderPersona",
    "PrivateReaderReaction",
    "PlatformPost",
    "CrossReaction",
    "SimulationRun",
    "BookPredictionReport",
    "DraftComparisonReport",
    "BookSimProviderRouter",
    "RouteSelection",
]
